### ISSUE TITLE
Error installing requirements

### ISSUE THREAD

**Issue by ajnachakra** [RhinoSecurityLabs/Security-Research#2]
`$ pip install -r requirements.txt
Collecting argparse (from -r requirements.txt (line 1))
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Collecting requests (from -r requirements.txt (line 2))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 1.1MB/s 
Collecting dnspython (from -r requirements.txt (line 3))
  Downloading dnspython-1.15.0-py2.py3-none-any.whl (177kB)
    100% |████████████████████████████████| 184kB 1.8MB/s 
Collecting dnslib (from -r requirements.txt (line 4))
  Downloading dnslib-0.9.7.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 2.6MB/s 
Collecting netaddr (from -r requirements.txt (line 5))
  Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 555kB/s 
Collecting sqlite3 (from -r requirements.txt (line 6))
  Downloading sqlite3-99.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xf/j6d7cpsn4qq7rht_ydj1r2zr001118/T/pip-build-6JTwrA/sqlite3/setup.py", line 2, in <module>
        raise RuntimeError("Package 'sqlite3' must not be downloaded from pypi")
    RuntimeError: Package 'sqlite3' must not be downloaded from pypi
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xf/j6d7cpsn4qq7rht_ydj1r2zr001118/T/pip-build-6JTwrA/sqlite3/
`

Environment:
`$ pip -V
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)`
`$ python -V
Python 2.7.10
`
OS X Sierra 10.12.6

**Comment by d0t1q** [comment]
sqlite's install should be done via the install_deps.sh file

**Comment by pmzhou** [comment]
pip install -r requirements.txt generates an error "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UML8dA/sqlite3/"
